// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGsj6iJE8hUv5RKD7jTGDnSohDT_VVjkQ',
    appId: '1:18406789005:web:5bd0ad0b383fa0d0b7b7c4',
    messagingSenderId: '18406789005',
    projectId: 'project-appdev-75928',
    authDomain: 'project-appdev-75928.firebaseapp.com',
    storageBucket: 'project-appdev-75928.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl1OeieGP1zXVj6kPLYBAmU9Ahy40hjVc',
    appId: '1:18406789005:android:fe6c29ab3ca0171eb7b7c4',
    messagingSenderId: '18406789005',
    projectId: 'project-appdev-75928',
    storageBucket: 'project-appdev-75928.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNuBxZqTnBVkOicaOvck2Y6owJC4rphcM',
    appId: '1:18406789005:ios:8158db5fa787bf12b7b7c4',
    messagingSenderId: '18406789005',
    projectId: 'project-appdev-75928',
    storageBucket: 'project-appdev-75928.appspot.com',
    iosBundleId: 'com.example.projectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNuBxZqTnBVkOicaOvck2Y6owJC4rphcM',
    appId: '1:18406789005:ios:8158db5fa787bf12b7b7c4',
    messagingSenderId: '18406789005',
    projectId: 'project-appdev-75928',
    storageBucket: 'project-appdev-75928.appspot.com',
    iosBundleId: 'com.example.projectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGsj6iJE8hUv5RKD7jTGDnSohDT_VVjkQ',
    appId: '1:18406789005:web:725db49db4fd4094b7b7c4',
    messagingSenderId: '18406789005',
    projectId: 'project-appdev-75928',
    authDomain: 'project-appdev-75928.firebaseapp.com',
    storageBucket: 'project-appdev-75928.appspot.com',
  );

}